# This file was automatically generated by pywxrc, do not edit by hand.
# -*- coding: UTF-8 -*-

import wx
import wx.xrc as xrc

__res = None

def get_resources():
    """ This function provides access to the XML resources in this module."""
    global __res
    if __res == None:
        __init_resources()
    return __res


class xrcMainFrame(wx.Frame):
    def PreCreate(self, pre):
        """ This function is called during the class's initialization.
        
        Override it for custom setup before the window is created usually to
        set additional window styles using SetWindowStyle() and SetExtraStyle()."""
        pass

    def __init__(self, parent):
        # Two stage creation (see http://wiki.wxpython.org/index.cgi/TwoStageCreation)
        pre = wx.PreFrame()
        self.PreCreate(pre)
        get_resources().LoadOnFrame(pre, parent, "MainFrame")
        self.PostCreate(pre)

        # create attributes for the named items in this container
        self.ID_NAME = xrc.XRCCTRL(self, "ID_NAME")
        self.ID_TEXT = xrc.XRCCTRL(self, "ID_TEXT")
        self.ID_SEND_BUTTON = xrc.XRCCTRL(self, "ID_SEND_BUTTON")
        self.ID_SCROLL_WINDOW = xrc.XRCCTRL(self, "ID_SCROLL_WINDOW")
        self.ID_LIST_CTRL = xrc.XRCCTRL(self, "ID_LIST_CTRL")
        self.ID_HTML = xrc.XRCCTRL(self, "ID_HTML")
        self.StatusBar = xrc.XRCCTRL(self, "StatusBar")



# ------------------------ Resource data ----------------------

def __init_resources():
    global __res
    __res = xrc.EmptyXmlResource()

    __res.Load('chat.xrc')
